name: github workflow exploration
on: [push, workflow_dispatch]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: install dependencies
      run: npm ci
    - name: lint code
      run: npm run lint
    - name: test code
      run: npm run test
    - name: build app
      run: npm run build # error handling test - no error
  deploy_app:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: build project
        run: npm run build
      - name: deploy
        run: echo "deploying"