name: gha error handling
on: [issues, workflow_dispatch]
jobs:
  notify_owner:
    runs-on: ubuntu-latest
    steps:
    - name: get issue event data
      run: |
        echo "[erorrs have occurred]"
        echo "${{ toJSON(github.event) }}"


